### ISSUE TITLE
Babelify/Babel-Deps upgrade to v7

### ISSUE THREAD

**Issue by jeffscottward** [cypress-io/cypress-browserify-preprocessor#11]
- Operating System: `MacOS 10.13.6`
- Cypress Version: `"cypress": "^3.0.2"`
- Browser Version: N/A

### Is this a Feature or Bug?
"Feature" (Bug: dependency is 2 years out of date)

### Current behavior:
Any use of newer javascript language features, that have come to be an expectation for frontend developers, like the spread operator ( ... ) or Async/Await, are unavailable and the dev's tests will fail. 

For our use:
Next.js, is fast becoming the standard of modern JS development frameworks, and it uses Babel 7.

### Desired behavior:
For cypress to be able to run our tests that make fair assumptions about language feature support in 2018.

### How to reproduce:
Run any test in cypress with some of the newer language features like `...` and `async/await`

### Additional Info (images, stack traces, etc)
`babelify` is now at version 9.
this repo uses babelify 7.3.0 and has Babel v6 peer deps
```
"babel-plugin-add-module-exports": "0.2.1"
"babel-preset-env": "1.6.0"
"babel-preset-react": "6.24.1"
```

**Comment by brian-mann** [comment]
Have you tried https://github.com/cypress-io/cypress-webpack-preprocessor by chance?

Also @chrisbreiding what are the chances we can get this upgraded? We've noticed that `async/await` does not work with the current version.

**Comment by bahmutov** [comment]
And we can set up renovate app to keep updating dependencies

**Comment by chrisbreiding** [comment]
I agree we should update the deps, but which language features gets transpiled is an orthogonal concern. You can configure this preprocessor to transpile whichever language features you need with the `'file:preprocessor'` plugin event as detailed in the readme.
