### ISSUE TITLE
need to expose browserify object not just options

### ISSUE THREAD

**Issue by baerrach** [cypress-io/cypress-browserify-preprocessor#28]
- Cypress Version:
```
    "@cypress/browserify-preprocessor": "^2.1.1",
```

### Is this a Feature or Bug?
Feature

### Current behavior:
There is no way to call any of the methods on the browserify object `bundler` created by cypress-browserify-preprocessor.

For example [ignore()](https://github.com/browserify/browserify#bignorefile) can't be used to work-around problems like:
* https://github.com/brianc/node-postgres/issues/1894
* https://github.com/sequelize/sequelize/issues/3781

### Desired behavior:
Expose the `bundler` so that Cypress user-land code can call any methods it needs

**Comment by chrisbreiding** [comment]
You can achieve this with the [`onBundle`](https://github.com/cypress-io/cypress-browserify-preprocessor#onbundle) option.

**Comment by baerrach** [comment]
Grr. I'm sure I checked that `bundler` wasn't passed into a function like that.

Cheers
