### ISSUE TITLE
Improve error message when attempting to compile TypeScript file and typescript support is not enabled

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress-browserify-preprocessor#47]
### Current behavior:

If you don't pass the `typescript` option, but have TypeScript files, it results in a syntax error. 

```
SyntaxError: Unexpected token (3:10) while parsing /path/to/project/cypress/integration/typescript_spec.ts while parsing file: /path/to/project/cypress/integration/typescript_spec.ts
```

See also this [issue comment](https://github.com/cypress-io/cypress-webpack-preprocessor/issues/79#issuecomment-625693277).

This is particularly problematic in the default Cypress behavior, since we try to pass the `typescript` option automatically by auto-detecting it. If we fail to find it and don't pass the option, but the user has TypeScript files, it fails at runtime with the above cryptic syntax error.

### Desired behavior:

We should error early if attempting to compile a `.ts` or `.tsx` file and the `typescript` option is not set. In the error message, we can make it clear what went wrong and provide remediation options.

### How to reproduce:

Create a TypeScript spec (`cypress/integration/typescript_spec.js`) and add some TypeScript-specific syntax:

```typescript
interface Foo {
  baz: string
}
```

Run Cypress and it will fail with a syntax error.

**Comment by mike-hogan** [comment]
@chrisbreiding this suggests that if I pass the `typescript` option, things will work.  Where and how do I pass this option?

Thanks

**Comment by chrisbreiding** [comment]
You can use it by using this package directly. Check out the [installation and usage](https://github.com/cypress-io/cypress-browserify-preprocessor#installation) directions the the [typescript](https://github.com/cypress-io/cypress-browserify-preprocessor#typescript) directions. 

Cypress uses this package under the hood and tries to auto-detect the path to your typescript installation, but it seems that may not work in all cases, so providing the path manually might make it work.
