### ISSUE TITLE
Cannot correctly configure Typescript according to documentation - will not run

### ISSUE THREAD

**Issue by sethreidnz** [cypress-io/cypress-browserify-preprocessor#55]
- Operating System: MacOS
- Cypress Version: 4.7
- Browser Version: Chrome 85

### Is this a Feature or Bug?

A bug I think. Or at least a problem with the instructions on getting setup with TypeScript

### Current behavior:

I have included the typescript option, as well as the other that are described in the [README](https://github.com/cypress-io/cypress-browserify-preprocessor#browserifyoptions) (really I figured out how to pass the "typescript option" from [this issue](https://github.com/cypress-io/cypress-browserify-preprocessor/pull/52)) like so:

```
const browserify = require('@cypress/browserify-preprocessor')

module.exports = (on) => {
  on(
    'file:preprocessor',
    browserify({
      typescript: require.resolve('typescript'),
      browserifyOptions: {
        extensions: ['.js', '.ts'],
        plugin: [['tsify']],
      },
    })
  )

  on('before:browser:launch', (browser = {}, launchOptions) => {
    if (browser.family === 'chromium' && browser.name !== 'electron') {
      launchOptions.args.push('--disable-setuid-sandbox')
      launchOptions.args.push('--flag-switches-begin')
      launchOptions.args.push('--disable-features=CookiesWithoutSameSiteMustBeSecure')
      launchOptions.args.push('--flag-switches-end')
      launchOptions.args.push('--no-sandbox')
      launchOptions.args.push('--disable-dev-shm-usage')

      // whatever you return here becomes the launchOptions
      return launchOptions
    }
  })
}
```

But I continue to get this error:

```
Error: Error running @cypress/browserify-preprocessor:

You are attempting to preprocess a TypeScript file, but do not have TypeScript configured. Pass the 'typescript' option to enable TypeScript support.
```

It looks like in the source that it is reading from the `typescript` property, but I'm unsure what I've done wrong here? 

https://github.com/cypress-io/cypress-browserify-preprocessor/blob/master/index.js#L194

### Desired behavior:

I can write my tests in .ts files and also setup my browserify options in the plugin file. I need to be able to spy on the type of browser as in the above for my test.

### How to reproduce:

Setup an empty project using typescript for example by [following these instructions](https://basarat.gitbook.io/typescript/intro-1/cypress). Add a typescript test. Then try to add the above code to your plugins file and run the test.

**Comment by sethreidnz** [comment]
Apologies! I was working on two version of my tests, one in the old JS and one in TS. And somehow had the plugins file mixed up so I wasn't actually making the change in the right place... I will try to make a PR to the docs to make it more clear how to get setup in Typescript though...

**Comment by sunpietro** [comment]
How did you managed to make it running? Can you share the config?

**Comment by kosmotaur** [comment]
> Apologies! I was working on two version of my tests, one in the old JS and one in TS. And somehow had the plugins file mixed up so I wasn't actually making the change in the right place... I will try to make a PR to the docs to make it more clear how to get setup in Typescript though...

any luck with that? :)
