### ISSUE TITLE
Debug@4.1.1 is deprecated due to ReDos regression

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/cypress-browserify-preprocessor#63]
- Operating System: Pop_OS 20.04! (Ubuntu 20.04)
- Cypress Version: 6.8.0
- Browser Version: Firefox 87.0

### Is this a Feature or Bug?

This is a dependency bug.

### Current behavior:

You're [currently using](https://github.com/cypress-io/cypress-browserify-preprocessor/blob/master/package.json#L35) `debug@4.1.1` which prints installation warnings:

```
➤ YN0061: │ debug@npm:4.1.1 is deprecated: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```

### Desired behavior:

You should upgrade that `debug` dependency to get rid of that installation warning for new users.

### How to reproduce:

1. Run a fresh install of `@cypress/code-coverage` (which depends on this package).
2. See installation warning.

**Comment by chrisbreiding** [comment]
Now using [`debug@^4.3.2`](https://github.com/cypress-io/cypress-browserify-preprocessor/blob/2b1c1f4f203d2804ca37d0967be97ede419e4b75/package.json#L35), so this issue should be resolved.
