### ISSUE TITLE
3.0.2 release failed in CircleCi

### ISSUE THREAD

**Issue by tomwkelly** [cypress-io/cypress-browserify-preprocessor#90]
- Operating System: N/A
- Cypress Version: N/A
- Browser Version: N/A

### Is this a Feature or Bug?
Bug

### Current behavior:
CircleCi pipeline step "npm run semantic-release" failed but returned 0 exit code on latest release:  [https://app.circleci.com/pipelines/github/cypress-io/cypress-browserify-preprocessor/113/workflows/46d26aaa-9fdf-47ef-8337-9048a70dcf12/jobs/191](https://app.circleci.com/pipelines/github/cypress-io/cypress-browserify-preprocessor/113/workflows/46d26aaa-9fdf-47ef-8337-9048a70dcf12/jobs/191)

### Desired behavior:
Release passes and updates package to 3.0.2

### How to reproduce:
Visit [https://app.circleci.com/pipelines/github/cypress-io/cypress-browserify-preprocessor/113/workflows/46d26aaa-9fdf-47ef-8337-9048a70dcf12/jobs/191](https://app.circleci.com/pipelines/github/cypress-io/cypress-browserify-preprocessor/113/workflows/46d26aaa-9fdf-47ef-8337-9048a70dcf12/jobs/191)

### Additional Info (images, stack traces, etc)
Could possibly be fixed by [https://github.com/cypress-io/cypress-browserify-preprocessor/pull/76](https://github.com/cypress-io/cypress-browserify-preprocessor/pull/76)

**Comment by Kryword** [comment]
Any news on this? We would like to have the new 3.0.2 version that removes one vulnerability on npm audit. But it's not published because of this failed CircleCI run.

**Comment by chrisbreiding** [comment]
I fixed the issue with semantic release and v3.0.2 has been successfully released: https://www.npmjs.com/package/@cypress/browserify-preprocessor/v/3.0.2
